# Generated by Django 2.2.6 on 2020-05-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0002_auto_20200518_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Favoritos', models.ManyToManyField(to='Sramais.Ramais')),
            ],
        ),
    ]
