# Generated by Django 2.2.6 on 2020-05-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0002_favoritos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favoritos',
            new_name='Favorito',
        ),
    ]
