# Generated by Django 2.2.6 on 2020-05-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0003_auto_20200505_0744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
