# Generated by Django 2.2.6 on 2020-05-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0004_auto_20200518_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='Favoritos',
            new_name='ramais',
        ),
    ]
