# Generated by Django 2.2.6 on 2020-05-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0005_favorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
