# Generated by Django 2.2.6 on 2020-05-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0007_auto_20200519_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ramais',
            old_name='nome',
            new_name='name',
        ),
    ]
