# Generated by Django 2.2.6 on 2020-05-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0007_auto_20200510_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramais',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='whatsapp'),
        ),
    ]
