# Generated by Django 2.2.6 on 2020-05-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0008_auto_20200520_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ramais',
            old_name='name',
            new_name='nome',
        ),
    ]
