# Generated by Django 2.2.6 on 2020-05-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0008_auto_20200510_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramais',
            name='email',
            field=models.EmailField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ramais',
            name='nome',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ramais',
            name='ramal',
            field=models.DecimalField(decimal_places=0, max_digits=4, unique=True),
        ),
        migrations.AlterField(
            model_name='ramais',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='Sramais.Unidade'),
        ),
    ]
