# Generated by Django 2.2.6 on 2020-05-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0009_auto_20200510_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramais',
            name='email',
        ),
    ]
