# Generated by Django 2.2.6 on 2020-05-25 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0009_auto_20200520_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
