# Generated by Django 2.2.6 on 2020-05-13 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0010_remove_ramais_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramais',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sramais.Unidade'),
        ),
    ]
