# Generated by Django 2.2.6 on 2020-05-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0011_auto_20200513_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramais',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sramais.Unidade'),
        ),
    ]
