# Generated by Django 2.2.6 on 2020-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0011_auto_20200525_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramais',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
