# Generated by Django 2.2.6 on 2020-05-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sramais', '0014_auto_20200513_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramais',
            name='unidade',
        ),
        migrations.AddField(
            model_name='ramais',
            name='unidade',
            field=models.ManyToManyField(null=True, to='Sramais.Unidade'),
        ),
    ]
